@startuml
rectangle "depending on fs" {
  object CLIEngine
  object Config
  object Plugins
}
object Linter
object ConfigCache
object ConfigData
object Environments
object Rules
object Parser
object Plugin
object Environment
object Rule

CLIEngine *--> Linter
CLIEngine *--> Config
Config --> Linter
Config *--> ConfigCache : "register"
Config *--> Plugins : "use"
Config ..> ConfigData : "load"
Config ..> Environments : "use"
Plugins --> Environments : "register"
Plugins --> Linter
Plugins ..> Rules : "register"
Plugins *--> Plugin : "load"
Linter *--> Parser : "load"
Linter *--> Rules : "use"
Linter *--> Environments : "use"
Linter ..> ConfigData : "use"
Environments --> Environment
Rules --> Rule
Plugin *--> Rule
Plugin *--> Environment
@enduml
