@startuml
rectangle "depending on fs" {
  object CLIEngine
  object FileEnumerator
  object ConfigArrayFactory
}
object Linter
object ConfigArray
object Parser
object Plugin
object Rule
object Environment

CLIEngine *--> Linter
CLIEngine *--> FileEnumerator
Linter ..> ConfigArray
FileEnumerator *--> ConfigArrayFactory
ConfigArrayFactory ..> ConfigArray : "load"
ConfigArrayFactory ..> Parser : "load"
ConfigArrayFactory ..> Plugin : "load"
ConfigArray o--> Parser
ConfigArray o--> Plugin
Plugin *--> Rule
Plugin *--> Environment
@enduml
